#!/bin/bash
set -euo pipefail

#
# Bootstrap script for Firecracker + Kata Containers on k3s nodes
#
# This script prepares k3s nodes to run Firecracker-based GitHub Actions runners:
# 1. Enables KVM (checks /dev/kvm access)
# 2. Configures containerd with device mapper snapshotter
# 3. Creates device mapper pool for Firecracker
# 4. Restarts k3s to apply configuration
#
# SECURITY: This script modifies system configuration and requires root access.
# Review carefully before running.
#
# Usage:
#   sudo ./bootstrap/setup-firecracker-nodes.sh
#
# Prerequisites:
#   - k3s already installed
#   - Root access
#   - At least 10GB free space for devmapper pool
#

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root (use sudo)"
   exit 1
fi

log_info "Starting Firecracker node bootstrap..."

# Step 1: Check KVM availability
log_info "Checking KVM availability..."
if [[ ! -e /dev/kvm ]]; then
    log_error "/dev/kvm not found. KVM is required for Firecracker."
    log_error "Check if:"
    log_error "  1. CPU supports virtualization (Intel VT-x or AMD-V)"
    log_error "  2. Virtualization is enabled in BIOS"
    log_error "  3. kvm kernel module is loaded (modprobe kvm kvm_intel/kvm_amd)"
    exit 1
fi

if [[ ! -r /dev/kvm ]] || [[ ! -w /dev/kvm ]]; then
    log_warn "/dev/kvm exists but is not readable/writable"
    log_info "Setting permissions on /dev/kvm..."
    chmod 666 /dev/kvm
fi

log_info "✓ KVM is available at /dev/kvm"

# Step 2: Check k3s installation
log_info "Checking k3s installation..."
if ! command -v k3s &> /dev/null; then
    log_error "k3s not found. Please install k3s first."
    exit 1
fi

K3S_VERSION=$(k3s --version | head -n1)
log_info "✓ Found k3s: $K3S_VERSION"

# Step 3: Backup existing containerd config
CONTAINERD_CONFIG="/var/lib/rancher/k3s/agent/etc/containerd/config.toml"
CONTAINERD_TEMPLATE="/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl"

log_info "Backing up containerd configuration..."
if [[ -f "$CONTAINERD_CONFIG" ]]; then
    cp "$CONTAINERD_CONFIG" "$CONTAINERD_CONFIG.backup.$(date +%Y%m%d_%H%M%S)"
    log_info "✓ Backup created"
fi

# Step 4: Configure device mapper storage
log_info "Setting up device mapper pool for Firecracker..."

# Check if device mapper is already configured
if [[ -f /var/lib/containerd/io.containerd.snapshotter.v1.devmapper/metadata.db ]]; then
    log_warn "Device mapper pool already exists, skipping creation"
else
    # Create sparse files for device mapper pool
    # Pool: 100GB thin pool, Data: 90GB, Metadata: 10GB
    POOL_SIZE=$((90 * 1024))  # 90GB in MB
    META_SIZE=$((10 * 1024))  # 10GB in MB

    log_info "Creating device mapper pool (this may take a few minutes)..."

    mkdir -p /var/lib/containerd/devmapper

    # Create sparse files
    truncate -s "${POOL_SIZE}M" /var/lib/containerd/devmapper/data
    truncate -s "${META_SIZE}M" /var/lib/containerd/devmapper/metadata

    # Create loop devices
    DATA_LOOP=$(losetup --find --show /var/lib/containerd/devmapper/data)
    META_LOOP=$(losetup --find --show /var/lib/containerd/devmapper/metadata)

    log_info "Data loop: $DATA_LOOP"
    log_info "Metadata loop: $META_LOOP"

    # Create thin pool
    SECTOR_SIZE=512
    DATA_SIZE="$(blockdev --getsize64 -q ${DATA_LOOP})"
    LENGTH_SECTORS=$(bc <<< "${DATA_SIZE}/${SECTOR_SIZE}")

    dmsetup create containerd-pool \
        --table "0 ${LENGTH_SECTORS} thin-pool ${META_LOOP} ${DATA_LOOP} 128 32768 1 skip_block_zeroing"

    log_info "✓ Device mapper pool created"
fi

# Step 5: Configure containerd for device mapper
log_info "Configuring containerd with device mapper snapshotter..."

cat > "$CONTAINERD_TEMPLATE" <<'EOF'
# Kata Containers + Firecracker configuration for k3s
# Generated by bootstrap/setup-firecracker-nodes.sh

version = 2

# Use device mapper as default snapshotter (required for Firecracker)
[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "devmapper"
  default_runtime_name = "runc"

# Device mapper configuration
[plugins."io.containerd.snapshotter.v1.devmapper"]
  pool_name = "containerd-pool"
  root_path = "/var/lib/containerd/io.containerd.snapshotter.v1.devmapper"
  base_image_size = "10GB"
  discard_blocks = true

# Kata runtime configurations (installed by kata-deploy)
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-fc]
  runtime_type = "io.containerd.kata-fc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

# Import k3s defaults
[plugins."io.containerd.grpc.v1.cri"]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  enable_unprivileged_ports = true
  enable_unprivileged_icmp = true

[plugins."io.containerd.grpc.v1.cri".cni]
  bin_dir = "/var/lib/rancher/k3s/data/current/bin"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"
EOF

log_info "✓ Containerd configured for device mapper"

# Step 6: Create systemd service to restore loop devices on boot
log_info "Creating systemd service for loop device persistence..."

cat > /etc/systemd/system/containerd-devmapper-setup.service <<'EOF'
[Unit]
Description=Setup loop devices for containerd devmapper
Before=k3s.service
DefaultDependencies=no

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c '\
  if [[ ! -e /dev/mapper/containerd-pool ]]; then \
    DATA_LOOP=$(losetup --find --show /var/lib/containerd/devmapper/data); \
    META_LOOP=$(losetup --find --show /var/lib/containerd/devmapper/metadata); \
    DATA_SIZE=$(blockdev --getsize64 -q ${DATA_LOOP}); \
    LENGTH_SECTORS=$((DATA_SIZE/512)); \
    dmsetup create containerd-pool --table "0 ${LENGTH_SECTORS} thin-pool ${META_LOOP} ${DATA_LOOP} 128 32768 1 skip_block_zeroing"; \
  fi'

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable containerd-devmapper-setup.service
log_info "✓ Systemd service created and enabled"

# Step 7: Restart k3s to apply configuration
log_info "Restarting k3s to apply configuration..."
systemctl restart k3s

# Wait for k3s to be ready
log_info "Waiting for k3s to be ready..."
sleep 10

if systemctl is-active --quiet k3s; then
    log_info "✓ k3s restarted successfully"
else
    log_error "k3s failed to restart. Check logs: journalctl -u k3s -f"
    exit 1
fi

# Step 8: Verify configuration
log_info "Verifying configuration..."

# Check if containerd is using devmapper
if k3s crictl info | grep -q "devmapper"; then
    log_info "✓ Containerd is using device mapper snapshotter"
else
    log_warn "Device mapper not detected in containerd config. Manual verification needed."
fi

# Summary
echo ""
log_info "========================================="
log_info "Firecracker node bootstrap complete!"
log_info "========================================="
log_info ""
log_info "Next steps:"
log_info "  1. Deploy the GitHub runners stack:"
log_info "     pulumi up -s dev"
log_info ""
log_info "  2. Verify Kata installation:"
log_info "     kubectl get ds -n kube-system kata-deploy"
log_info ""
log_info "  3. Check runner deployment:"
log_info "     kubectl get pods -n github-runners"
log_info ""
log_info "Configuration files:"
log_info "  - Containerd: $CONTAINERD_TEMPLATE"
log_info "  - Devmapper pool: /dev/mapper/containerd-pool"
log_info "  - Systemd service: /etc/systemd/system/containerd-devmapper-setup.service"
log_info ""
log_info "To rollback, restore from backup:"
log_info "  ls -la $CONTAINERD_CONFIG.backup.*"
log_info "========================================="
